-- Tabel untuk surat undangan
CREATE TABLE IF NOT EXISTS surat_undangan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tanggal_surat DATE NOT NULL,
  nomor_surat VARCHAR(100) NOT NULL,
  perihal VARCHAR(255) NOT NULL,
  nama VARCHAR(200) NOT NULL,
  alamat TEXT NOT NULL,
  tembusan_kepada TEXT,
  hari_tanggal VARCHAR(100) NOT NULL,
  tempat_pelaksanaan VARCHAR(255) NOT NULL,
  jam TIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
